name: Undeploy contract from staging
on:
  pull_request:
    types: [closed]
    paths:
      - contract/**

defaults:
  run:
    working-directory: ./contract

jobs:
  cleanup-staging:
    name: Cleanup staging account
    runs-on: ubuntu-latest
    env:
      NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID: gh-${{ github.event.number }}.${{ vars.BOS_TESTNET_SIGNER_ACCOUNT_ID }}
      BOS_BUILDDAO_TESTNET_SIGNER_PUBLIC_KEY: "ed25519:6ycWXZES2zEGPurZqP35AUQx92aAzuS7r9ea1GcSQQiT"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/near-cli-rs/releases/download/v0.11.1/near-cli-rs-installer.sh | sh
      - name: Remove staging account
        run: |
          near account delete-account "${{ env.NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID }}" \
            beneficiary "${{ vars.BOS_TESTNET_SIGNER_ACCOUNT_ID }}" \
            network-config "testnet" \
            sign-with-plaintext-private-key \
              --signer-public-key "${{ env.BOS_BUILDDAO_TESTNET_SIGNER_PUBLIC_KEY }}" \
              --signer-private-key "${{ secrets.BOS_BUILDDAO_TESTNET_SIGNER_PRIVATE_KEY }}" \
            send
