name: Deploy contract to staging
on:
  pull_request:
    paths:
      - contract/**

defaults:
  run:
    working-directory: ./contract

jobs:
  test:
    uses: ./.github/workflows/contract-test.yml

  contract-deploy-staging:
    name: Deploy to staging subaccount
    permissions:
      pull-requests: write
    needs: [test]
    runs-on: ubuntu-latest
    env:
      NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID: gh-${{ github.event.number }}.${{ vars.BOS_TESTNET_SIGNER_ACCOUNT_ID }}
      BOS_BUILDDAO_TESTNET_SIGNER_PUBLIC_KEY: "ed25519:6ycWXZES2zEGPurZqP35AUQx92aAzuS7r9ea1GcSQQiT"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/near-cli-rs/releases/download/v0.11.1/near-cli-rs-installer.sh | sh
      - name: Create staging account
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        run: |
          near account create-account fund-myself "${{ env.NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID }}" '3 NEAR' \
            use-manually-provided-public-key "${{ env.BOS_BUILDDAO_TESTNET_SIGNER_PUBLIC_KEY }}" \
            sign-as "${{ vars.BOS_TESTNET_SIGNER_ACCOUNT_ID }}" \
            network-config "testnet" \
            sign-with-plaintext-private-key \
              --signer-public-key "${{ env.BOS_BUILDDAO_TESTNET_SIGNER_PUBLIC_KEY }}" \
              --signer-private-key "${{ secrets.BOS_BUILDDAO_TESTNET_SIGNER_PRIVATE_KEY }}" \
            send

      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/download/cargo-near-v0.6.2/cargo-near-installer.sh | sh
      - name: Deploy to staging
        run: |
          cargo near deploy "${{ env.NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID }}" \
            without-init-call \
            network-config "testnet" \
            sign-with-plaintext-private-key \
              --signer-public-key "${{ env.BOS_BUILDDAO_TESTNET_SIGNER_PUBLIC_KEY }}" \
              --signer-private-key "${{ secrets.BOS_BUILDDAO_TESTNET_SIGNER_PRIVATE_KEY }}" \
            send

      - name: Comment on pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment "${{ github.event.number }}" --body "Staging contract is deployed to ["'`'"${{ env.NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID }}"'`'" account](https://explorer.testnet.near.org/accounts/${{ env.NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID }})"
