name: Deploy Components to Testnet

on:
  push:
    branches: [develop]
    paths:
      - apps/old/**

jobs:
  deploy-old-testnet:
    uses: nearbuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      build-env: "testnet"
      deploy-env: "testnet"
      bw-legacy: false
      app-name: "old"
      deploy-account-address: "buildhub.testnet"
      signer-account-address: "buildhub.testnet"
      signer-public-key: "ed25519:C4PKraMoeA21tnKvPda2x4JtvYdQ8e7NFgr43hKnsSxe"
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.BOS_BUILDHUB_TESTNET_SIGNER_PRIVATE_KEY }}
