name: Deploy Components to Testnet

on:
  push:
    branches: [develop]

jobs:
  deploy-testnet:
    uses: nearbuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      deploy-env: "testnet"
      app-name: "builddao"
      deploy-account-address: ${{ vars.BOS_TESTNET_SIGNER_ACCOUNT_ID }}
      signer-account-address: ${{ vars.BOS_TESTNET_SIGNER_ACCOUNT_ID }}
      signer-public-key: ${{ vars.BOS_TESTNET_SIGNER_PUBLIC_KEY }}
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.BOS_TESTNET_SIGNER_PRIVATE_KEY }}
